Update codeception.yml

diff --git a/.github/workflows/codeception.yml b/.github/workflows/codeception.yml
--- a/.github/workflows/codeception.yml
+++ b/.github/workflows/codeception.yml
@@ -1,82 +1,89 @@
-
-name: "Codeception Tests"
+name: Codeception Tests [centralised]
 
 on:
-    schedule:
-        - cron: '0 3 * * 1,3,5'
-    pull_request:
-        branches:
-            - "[0-9]+.[0-9]+"
-            - "[0-9]+.x"
+    workflow_dispatch:
     push:
         branches:
             - "[0-9]+.[0-9]+"
             - "[0-9]+.x"
+            - "feature-*"
+    pull_request:
+        types: [ opened, synchronize, reopened ]
 
 env:
     OPENDXP_PROJECT_ROOT: ${{ github.workspace }}
-    APP_ENV: test
-    OPENDXP_TEST: 1
-    OPENDXP_TEST_DB_DSN: "mysql://root@127.0.0.1:33006/opendxp_test"
 
 jobs:
-    codeception-tests:
-        name: "Codeception tests"
-        runs-on: "ubuntu-20.04"
-        continue-on-error: ${{ matrix.experimental }}
-        strategy:
-            matrix:
-                include:
-                    - { php-version: 8.1, database: "mariadb:10.11", opendxp_version: "", dependencies: highest, experimental: false, require_admin_bundle: true }
-                    - { php-version: 8.2, database: "mariadb:10.11", opendxp_version: "", dependencies: highest, experimental: false, require_admin_bundle: true }
-                    - { php-version: 8.3, database: "mariadb:10.11", opendxp_version: "1.x-dev", dependencies: highest, experimental: true, require_admin_bundle: true }
-        services:
-            mariadb:
-                image: "${{ matrix.database }}"
-                ports:
-                    - 33006:3306
-                env:
-                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
-
+    setup-matrix:
+        runs-on: ubuntu-latest
+        outputs:
+            php_versions: ${{ steps.parse-php-versions.outputs.php_versions }}
+            matrix: ${{ steps.set-matrix.outputs.matrix }}
         steps:
-            - name: "Checkout code"
-              uses: "actions/checkout@v2"
+            -   name: Checkout code
+                uses: actions/checkout@v4
 
-            - name: "Install PHP"
-              uses: "shivammathur/setup-php@v2"
-              with:
-                  coverage: "none"
-                  extensions: imagick
-                  ini-values: display_errors=On, display_startup_errors=On, error_reporting=32767
-                  php-version: "${{ matrix.php-version }}"
+            -   name: Checkout reusable workflow repo
+                uses: actions/checkout@v4
+                with:
+                    repository: open-dxp/workflows-collection-public
+                    ref: main
+                    path: reusable-workflows
 
-            - name: Verify MariaDB connection
-              run: |
-                  cp .github/ci/files/.my.cnf ~/.my.cnf
-                  while ! mysqladmin ping --silent; do
-                    sleep 1
-                  done
+            -   name: Parse PHP versions from composer.json
+                id: parse-php-versions
+                run: |
+                    if [ -f composer.json ]; then
+                      php_versions=$(jq -r '.require.php' composer.json | grep -oP '\d+\.\d+' | tr '\n' ',' | sed 's/,$//')
+                      if [ -z "$php_versions" ]; then
+                        echo "No PHP versions found in composer.json"
+                        echo "Setting default PHP value"
+                        echo "php_versions=default" >> $GITHUB_OUTPUT
+                      else
+                        echo "php_versions=$php_versions" >> $GITHUB_OUTPUT
+                        echo "#### php versions #### : $php_versions"
+                      fi
+                    else
+                      echo "composer.json not found"
+                      exit 1
+                    fi
 
-            - name: "Setup OpenDxp environment"
-              env:
-                  REQUIRE_ADMIN_BUNDLE: "${{ matrix.require_admin_bundle }}"
-              run: |
-                  mysql -e "CREATE DATABASE opendxp_test CHARSET=utf8mb4;"
-                  chmod 755 .github/ci/scripts/setup-opendxp-environment.sh
-                  .github/ci/scripts/setup-opendxp-environment.sh
+            -   name: Set up matrix
+                id: set-matrix
+                run: |
+                    php_versions="${{ steps.parse-php-versions.outputs.php_versions }}"
+                    
+                    MATRIX_JSON=$(cat reusable-workflows/codeception-tests-configuration/matrix-config.json)
+                    
+                    IFS=',' read -ra VERSIONS_ARRAY <<< "$php_versions"
+                    
+                    FILTERED_MATRIX_JSON=$(echo $MATRIX_JSON | jq --arg php_versions "$php_versions" '
+                    {
+                      matrix: [
+                        .configs[] |
+                        select(.php_version == $php_versions) |
+                        .matrix[]
+                      ]
+                    }')
+                    
+                    ENCODED_MATRIX_JSON=$(echo $FILTERED_MATRIX_JSON | jq -c .)
+                    
+                    echo "matrix=${ENCODED_MATRIX_JSON}" >> $GITHUB_OUTPUT
 
-            - name: "Update OpenDxp version"
-              env:
-                  OPENDXP_VERSION: "${{ matrix.opendxp_version }}"
-              run: |
-                  if [ ! -z "$OPENDXP_VERSION" ]; then
-                        composer require --no-update open-dxp/opendxp:"${OPENDXP_VERSION}"
-                  fi    
-
-            - name: "Install dependencies with Composer"
-              uses: "ramsey/composer-install@v2"
-              with:
-                  dependency-versions: "${{ matrix.dependencies }}"
-
-            - name: "Run Codeception"
-              run: "vendor/bin/codecept run -c . -vvv --xml"
+    codeception-tests:
+        needs: setup-matrix
+        strategy:
+            matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
+        uses: open-dxp/workflows-collection-public/.github/workflows/reusable-codeception-tests-centralized.yaml@main
+        with:
+            APP_ENV: test
+            OPENDXP_TEST: 1
+            PHP_VERSION: ${{ matrix.matrix.php-version }}
+            DATABASE: ${{ matrix.matrix.database }}
+            SERVER_VERSION: ${{ matrix.matrix.server_version }}
+            DEPENDENCIES: ${{ matrix.matrix.dependencies }}
+            EXPERIMENTAL: ${{ matrix.matrix.experimental }}
+            OPENDXP_VERSION: ${{ matrix.matrix.opendxp_version }}
+        secrets:
+            SSH_PRIVATE_KEY_OPENDXP_DEPLOYMENTS_USER: ${{ secrets.SSH_PRIVATE_KEY_OPENDXP_DEPLOYMENTS_USER }}
+            COMPOSER_OPENDXP_REPO_PACKAGIST_TOKEN: ${{ secrets.COMPOSER_OPENDXP_REPO_PACKAGIST_TOKEN }}
